
import java.awt.Color;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author farhaan
 */import java.awt.Color;
public class Assignment extends javax.swing.JInternalFrame {

    /**
     * Creates new form User_Details
     */
    Color DefaultColor,ClickedColor;
    public Assignment() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui=(BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        DefaultColor = new Color(0,153,204);
        ClickedColor = new Color(102,204,255);
        
        a3.setBackground(DefaultColor);
        a3.setBackground(DefaultColor);
        a3.setBackground(DefaultColor);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        a3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        a1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        a2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        wadestop = new javax.swing.JDesktopPane();

        setBackground(new java.awt.Color(0, 153, 204));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204), 2));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        a3.setBackground(new java.awt.Color(0, 153, 204));
        a3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        a3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a3MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                a3MousePressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Previous Year Paper");
        a3.add(jLabel3);

        jPanel5.add(a3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 230, 40));

        a1.setBackground(new java.awt.Color(0, 153, 204));
        a1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        a1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                a1MousePressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Weekly Assignments");
        a1.add(jLabel4);

        jPanel5.add(a1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 230, 40));

        a2.setBackground(new java.awt.Color(0, 153, 204));
        a2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        a2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a2MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                a2MousePressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Reference Question");
        a2.add(jLabel5);

        jPanel5.add(a2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 230, 40));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 430));

        javax.swing.GroupLayout wadestopLayout = new javax.swing.GroupLayout(wadestop);
        wadestop.setLayout(wadestopLayout);
        wadestopLayout.setHorizontalGroup(
            wadestopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );
        wadestopLayout.setVerticalGroup(
            wadestopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );

        getContentPane().add(wadestop, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 440, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void a3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a3MouseClicked
        // TODO add your handling code here:
        Previousyearpaper pyp=new Previousyearpaper();
        wadestop.removeAll();
        wadestop.add(pyp).setVisible(true);
    }//GEN-LAST:event_a3MouseClicked

    private void a3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a3MousePressed
        // TODO add your handling code here:
        a1.setBackground(DefaultColor);
        a2.setBackground(DefaultColor);
        a3.setBackground(ClickedColor);

    }//GEN-LAST:event_a3MousePressed

    private void a1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a1MouseClicked
        // TODO add your handling code here:
        Weelyassignment wa=new Weelyassignment();
        wadestop.removeAll();
        wadestop.add(wa).setVisible(true);
    }//GEN-LAST:event_a1MouseClicked

    private void a1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a1MousePressed
        // TODO add your handling code here:
        a1.setBackground(ClickedColor);
        a2.setBackground(DefaultColor);
        a3.setBackground(DefaultColor);
    }//GEN-LAST:event_a1MousePressed

    private void a2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a2MouseClicked
        // TODO add your handling code here:
        Referencepaper rp=new Referencepaper();
        wadestop.removeAll();
        wadestop.add(rp).setVisible(true);
    }//GEN-LAST:event_a2MouseClicked

    private void a2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a2MousePressed
        // TODO add your handling code here:
        a1.setBackground(DefaultColor);
        a2.setBackground(ClickedColor);
        a3.setBackground(DefaultColor);
    }//GEN-LAST:event_a2MousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel a1;
    private javax.swing.JPanel a2;
    private javax.swing.JPanel a3;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JDesktopPane wadestop;
    // End of variables declaration//GEN-END:variables
}
