
import java.awt.Color;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author farhaan
 */
public class Attendence extends javax.swing.JInternalFrame {

    /**
     * Creates new form User_Details
     */Color DefaultColor,ClickedColor;
    public Attendence() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui=(BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        DefaultColor = new Color(0,153,204);
        ClickedColor = new Color(102,204,255);
        
        a1.setBackground(DefaultColor);
        a2.setBackground(DefaultColor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jInternalFrame2 = new javax.swing.JInternalFrame();
        jInternalFrame3 = new javax.swing.JInternalFrame();
        jPanel5 = new javax.swing.JPanel();
        a1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        a2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        adestop = new javax.swing.JDesktopPane();

        setBackground(new java.awt.Color(0, 153, 204));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jInternalFrame1.setBackground(new java.awt.Color(0, 153, 204));
        jInternalFrame1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jInternalFrame2.setBackground(new java.awt.Color(0, 153, 204));
        jInternalFrame2.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jInternalFrame3.setBackground(new java.awt.Color(0, 153, 204));
        jInternalFrame3.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jInternalFrame2.getContentPane().add(jInternalFrame3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jInternalFrame1.getContentPane().add(jInternalFrame2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jInternalFrame1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204), 2));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        a1.setBackground(new java.awt.Color(0, 153, 204));
        a1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        a1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                a1MousePressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Exam Attendence");
        a1.add(jLabel4);

        jPanel5.add(a1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 230, 40));

        a2.setBackground(new java.awt.Color(0, 153, 204));
        a2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        a2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a2MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                a2MousePressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Lecture Attendence");
        a2.add(jLabel5);

        jPanel5.add(a2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 230, 40));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 430));

        javax.swing.GroupLayout adestopLayout = new javax.swing.GroupLayout(adestop);
        adestop.setLayout(adestopLayout);
        adestopLayout.setHorizontalGroup(
            adestopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );
        adestopLayout.setVerticalGroup(
            adestopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );

        getContentPane().add(adestop, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 470, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void a1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a1MouseClicked
        // TODO add your handling code here:
        Examattendence ea=new Examattendence();
        adestop.removeAll();
        adestop.add(ea).setVisible(true);
    }//GEN-LAST:event_a1MouseClicked

    private void a1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a1MousePressed
        // TODO add your handling code here:
        a1.setBackground(ClickedColor);
        a2.setBackground(DefaultColor);
    }//GEN-LAST:event_a1MousePressed

    private void a2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a2MouseClicked
        // TODO add your handling code here:
        Lectureattendence la=new Lectureattendence();
        adestop.removeAll();
        adestop.add(la).setVisible(true);
    }//GEN-LAST:event_a2MouseClicked

    private void a2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a2MousePressed
        // TODO add your handling code here:
        a1.setBackground(DefaultColor);
        a2.setBackground(ClickedColor);
    }//GEN-LAST:event_a2MousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel a1;
    private javax.swing.JPanel a2;
    private javax.swing.JDesktopPane adestop;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JInternalFrame jInternalFrame2;
    private javax.swing.JInternalFrame jInternalFrame3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
