
import java.awt.Color;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author farhaan
 */import java.awt.Color;
public class Exam_Performance extends javax.swing.JInternalFrame {

    /**
     * Creates new form User_Details
     */Color DefaultColor,ClickedColor;
    public Exam_Performance() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui=(BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        DefaultColor = new Color(0,153,204);
        ClickedColor = new Color(102,204,255);
        
        e1.setBackground(DefaultColor);
        e2.setBackground(DefaultColor);
        e3.setBackground(DefaultColor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        e3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        e1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        e2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        edestop = new javax.swing.JDesktopPane();

        setBackground(new java.awt.Color(0, 153, 204));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, -1));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204), 2));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        e3.setBackground(new java.awt.Color(0, 153, 204));
        e3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        e3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                e3MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                e3MousePressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Exam Result");
        e3.add(jLabel4);

        jPanel1.add(e3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 230, 40));

        e1.setBackground(new java.awt.Color(0, 153, 204));
        e1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        e1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                e1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                e1MousePressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Quiz Result");
        e1.add(jLabel5);

        jPanel1.add(e1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 230, 40));

        e2.setBackground(new java.awt.Color(0, 153, 204));
        e2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        e2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                e2MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                e2MousePressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Assignment Result");
        e2.add(jLabel6);

        jPanel1.add(e2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 230, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 440));

        javax.swing.GroupLayout edestopLayout = new javax.swing.GroupLayout(edestop);
        edestop.setLayout(edestopLayout);
        edestopLayout.setHorizontalGroup(
            edestopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );
        edestopLayout.setVerticalGroup(
            edestopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );

        getContentPane().add(edestop, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 440, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void e3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_e3MouseClicked
        // TODO add your handling code here:
        Examresult er=new Examresult();
        edestop.removeAll();
        edestop.add(er).setVisible(true);
    }//GEN-LAST:event_e3MouseClicked

    private void e3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_e3MousePressed
        // TODO add your handling code here:
        e1.setBackground(DefaultColor);
        e2.setBackground(DefaultColor);
        e3.setBackground(ClickedColor);
    }//GEN-LAST:event_e3MousePressed

    private void e1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_e1MouseClicked
        // TODO add your handling code here:
        Quizresult qr=new Quizresult();
        edestop.removeAll();
        edestop.add(qr).setVisible(true);
    }//GEN-LAST:event_e1MouseClicked

    private void e1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_e1MousePressed
        // TODO add your handling code here:
        e1.setBackground(ClickedColor);
        e2.setBackground(DefaultColor);
        e3.setBackground(DefaultColor);
    }//GEN-LAST:event_e1MousePressed

    private void e2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_e2MouseClicked
        // TODO add your handling code here:
        Assignmentresult ar=new Assignmentresult();
        edestop.removeAll();
        edestop.add(ar).setVisible(true);
    }//GEN-LAST:event_e2MouseClicked

    private void e2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_e2MousePressed
        // TODO add your handling code here:
        e1.setBackground(DefaultColor);
        e2.setBackground(ClickedColor);
        e3.setBackground(DefaultColor);
    }//GEN-LAST:event_e2MousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel e1;
    private javax.swing.JPanel e2;
    private javax.swing.JPanel e3;
    private javax.swing.JDesktopPane edestop;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
