/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author farhaan
 */
import java.lang.*;
import java.util.*;
import java.awt.Color;
import java.sql.*;
public class Homepage extends javax.swing.JFrame {
    
    

    
    Color DefaultColor,ClickedColor;
    public Homepage() {
        initComponents();
        this.setLocationRelativeTo(null);
        DefaultColor = new Color(0,153,204);
        ClickedColor = new Color(102,204,255);
        
        p1.setBackground(DefaultColor);
        p2.setBackground(DefaultColor);
        p3.setBackground(DefaultColor);
        p4.setBackground(DefaultColor);
        p5.setBackground(DefaultColor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        p5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        p1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        p2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        p3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        p4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        hdestop = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204), 2));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0), 2));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\farhaan\\Downloads\\e_3_230x150.png")); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204), 2));
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 150));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 150));

        p5.setBackground(new java.awt.Color(0, 153, 204));
        p5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        p5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p5MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                p5MousePressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Attendence");
        p5.add(jLabel2);

        jPanel1.add(p5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 230, 40));

        p1.setBackground(new java.awt.Color(0, 153, 204));
        p1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        p1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                p1MousePressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("User Details");
        p1.add(jLabel3);

        jPanel1.add(p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 230, 40));

        p2.setBackground(new java.awt.Color(0, 153, 204));
        p2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        p2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p2MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                p2MousePressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Lectures");
        p2.add(jLabel4);

        jPanel1.add(p2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 230, 40));

        p3.setBackground(new java.awt.Color(0, 153, 204));
        p3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        p3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p3MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                p3MousePressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Assignments");
        p3.add(jLabel5);

        jPanel1.add(p3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 230, 40));

        p4.setBackground(new java.awt.Color(0, 153, 204));
        p4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        p4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p4MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                p4MousePressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Exam Performance");
        p4.add(jLabel6);

        jPanel1.add(p4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 230, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 580));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204), 2));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, -10, 670, 160));

        javax.swing.GroupLayout hdestopLayout = new javax.swing.GroupLayout(hdestop);
        hdestop.setLayout(hdestopLayout);
        hdestopLayout.setHorizontalGroup(
            hdestopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );
        hdestopLayout.setVerticalGroup(
            hdestopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );

        getContentPane().add(hdestop, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 670, 430));

        setSize(new java.awt.Dimension(914, 586));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void p2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p2MousePressed
        // TODO add your handling code here:
        p1.setBackground(DefaultColor);
        p2.setBackground(ClickedColor);
        p3.setBackground(DefaultColor);
        p4.setBackground(DefaultColor);
        p5.setBackground(DefaultColor);
        
    }//GEN-LAST:event_p2MousePressed

    private void p3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p3MousePressed
        // TODO add your handling code here:
        p1.setBackground(DefaultColor);
        p2.setBackground(DefaultColor);
        p3.setBackground(ClickedColor);
        p4.setBackground(DefaultColor);
        p5.setBackground(DefaultColor);
        
    }//GEN-LAST:event_p3MousePressed

    private void p4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p4MousePressed
        // TODO add your handling code here:
        p1.setBackground(DefaultColor);
        p2.setBackground(DefaultColor);
        p3.setBackground(DefaultColor);
        p4.setBackground(ClickedColor);
        p5.setBackground(DefaultColor);
        
    }//GEN-LAST:event_p4MousePressed

    private void p5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p5MousePressed
        // TODO add your handling code here:
        p1.setBackground(DefaultColor);
        p2.setBackground(DefaultColor);
        p3.setBackground(DefaultColor);
        p4.setBackground(DefaultColor);
        p5.setBackground(ClickedColor);
    }//GEN-LAST:event_p5MousePressed

    private void p1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p1MousePressed
        // TODO add your handling code here:
        p1.setBackground(ClickedColor);
        p2.setBackground(DefaultColor);
        p3.setBackground(DefaultColor);
        p4.setBackground(DefaultColor);
        p5.setBackground(DefaultColor);
    }//GEN-LAST:event_p1MousePressed

    private void p1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p1MouseClicked
        // TODO add your handling code here:
        User_Details ud=new User_Details();
        hdestop.removeAll();
        hdestop.add(ud).setVisible(true);
    }//GEN-LAST:event_p1MouseClicked

    private void p2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p2MouseClicked
        // TODO add your handling code here:
        Lectures le=new Lectures();
        hdestop.removeAll();
        hdestop.add(le).setVisible(true);
    }//GEN-LAST:event_p2MouseClicked

    private void p3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p3MouseClicked
        // TODO add your handling code here:
        Assignment as=new Assignment();
        hdestop.removeAll();
        hdestop.add(as).setVisible(true);
    }//GEN-LAST:event_p3MouseClicked

    private void p4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p4MouseClicked
        // TODO add your handling code here:
        Exam_Performance ep=new Exam_Performance();
        hdestop.removeAll();
        hdestop.add(ep).setVisible(true);
    }//GEN-LAST:event_p4MouseClicked

    private void p5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p5MouseClicked
        // TODO add your handling code here:
        Attendence ep=new Attendence();
        hdestop.removeAll();
        hdestop.add(ep).setVisible(true);
    }//GEN-LAST:event_p5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Homepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane hdestop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel p1;
    private javax.swing.JPanel p2;
    private javax.swing.JPanel p3;
    private javax.swing.JPanel p4;
    private javax.swing.JPanel p5;
    // End of variables declaration//GEN-END:variables
}
