
import javax.swing.plaf.basic.BasicInternalFrameUI;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author farhaan
 */
public class Previousyearpaper extends javax.swing.JInternalFrame {

    /**
     * Creates new form Previousyearpaper
     */
    public Previousyearpaper() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui=(BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jToggleButton9 = new javax.swing.JToggleButton();
        jToggleButton18 = new javax.swing.JToggleButton();
        jToggleButton10 = new javax.swing.JToggleButton();
        jToggleButton11 = new javax.swing.JToggleButton();
        jToggleButton25 = new javax.swing.JToggleButton();
        jToggleButton26 = new javax.swing.JToggleButton();
        jToggleButton27 = new javax.swing.JToggleButton();
        jToggleButton28 = new javax.swing.JToggleButton();
        jToggleButton29 = new javax.swing.JToggleButton();
        jToggleButton30 = new javax.swing.JToggleButton();
        jToggleButton31 = new javax.swing.JToggleButton();
        jToggleButton33 = new javax.swing.JToggleButton();
        jToggleButton34 = new javax.swing.JToggleButton();
        jToggleButton35 = new javax.swing.JToggleButton();
        jToggleButton36 = new javax.swing.JToggleButton();
        jToggleButton32 = new javax.swing.JToggleButton();

        setPreferredSize(new java.awt.Dimension(460, 350));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToggleButton9.setBackground(new java.awt.Color(0, 153, 204));
        buttonGroup1.add(jToggleButton9);
        jToggleButton9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jToggleButton9.setText("Topic:5 Papers");
        jToggleButton9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204), 2));
        jToggleButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 140, -1));

        jToggleButton18.setBackground(new java.awt.Color(0, 153, 204));
        buttonGroup1.add(jToggleButton18);
        jToggleButton18.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jToggleButton18.setText("Topic:14 Papers");
        jToggleButton18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204), 2));
        jPanel1.add(jToggleButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 140, -1));

        jToggleButton10.setBackground(new java.awt.Color(0, 153, 204));
        buttonGroup1.add(jToggleButton10);
        jToggleButton10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jToggleButton10.setText("Topic:2 Papers");
        jToggleButton10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204), 2));
        jToggleButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 140, -1));

        jToggleButton11.setBackground(new java.awt.Color(0, 153, 204));
        buttonGroup1.add(jToggleButton11);
        jToggleButton11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jToggleButton11.setText("Topic:3 Papers");
        jToggleButton11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204), 2));
        jToggleButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton11ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 140, -1));

        jToggleButton25.setBackground(new java.awt.Color(0, 153, 204));
        buttonGroup1.add(jToggleButton25);
        jToggleButton25.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jToggleButton25.setText("Topic:6 Papers");
        jToggleButton25.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204), 2));
        jToggleButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton25ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton25, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 140, -1));

        jToggleButton26.setBackground(new java.awt.Color(0, 153, 204));
        buttonGroup1.add(jToggleButton26);
        jToggleButton26.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jToggleButton26.setText("Topic:8 Papers");
        jToggleButton26.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204), 2));
        jToggleButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton26ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton26, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 140, -1));

        jToggleButton27.setBackground(new java.awt.Color(0, 153, 204));
        buttonGroup1.add(jToggleButton27);
        jToggleButton27.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jToggleButton27.setText("Topic:4 Papers");
        jToggleButton27.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204), 2));
        jToggleButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton27ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton27, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 140, -1));

        jToggleButton28.setBackground(new java.awt.Color(0, 153, 204));
        buttonGroup1.add(jToggleButton28);
        jToggleButton28.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jToggleButton28.setText("Topic:7 Papers");
        jToggleButton28.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204), 2));
        jToggleButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton28ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton28, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 140, -1));

        jToggleButton29.setBackground(new java.awt.Color(0, 153, 204));
        buttonGroup1.add(jToggleButton29);
        jToggleButton29.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jToggleButton29.setText("Topic:11 Papers");
        jToggleButton29.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204), 2));
        jPanel1.add(jToggleButton29, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 140, -1));

        jToggleButton30.setBackground(new java.awt.Color(0, 153, 204));
        buttonGroup1.add(jToggleButton30);
        jToggleButton30.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jToggleButton30.setText("Topic:10 Papers");
        jToggleButton30.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204), 2));
        jPanel1.add(jToggleButton30, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 140, -1));

        jToggleButton31.setBackground(new java.awt.Color(0, 153, 204));
        buttonGroup1.add(jToggleButton31);
        jToggleButton31.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jToggleButton31.setText("Topic:1 Papers");
        jToggleButton31.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204), 2));
        jPanel1.add(jToggleButton31, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 140, -1));

        jToggleButton33.setBackground(new java.awt.Color(0, 153, 204));
        buttonGroup1.add(jToggleButton33);
        jToggleButton33.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jToggleButton33.setText("Topic:12 Papers");
        jToggleButton33.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204), 2));
        jPanel1.add(jToggleButton33, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 140, -1));

        jToggleButton34.setBackground(new java.awt.Color(0, 153, 204));
        buttonGroup1.add(jToggleButton34);
        jToggleButton34.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jToggleButton34.setText("Topic:15 Papers");
        jToggleButton34.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204), 2));
        jPanel1.add(jToggleButton34, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 140, -1));

        jToggleButton35.setBackground(new java.awt.Color(0, 153, 204));
        buttonGroup1.add(jToggleButton35);
        jToggleButton35.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jToggleButton35.setText("Topic:16 Papers");
        jToggleButton35.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204), 2));
        jPanel1.add(jToggleButton35, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 140, -1));

        jToggleButton36.setBackground(new java.awt.Color(0, 153, 204));
        buttonGroup1.add(jToggleButton36);
        jToggleButton36.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jToggleButton36.setText("Topic:13 Papers");
        jToggleButton36.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204), 2));
        jPanel1.add(jToggleButton36, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 140, -1));

        jToggleButton32.setBackground(new java.awt.Color(0, 153, 204));
        buttonGroup1.add(jToggleButton32);
        jToggleButton32.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jToggleButton32.setText("Topic:9 Papers");
        jToggleButton32.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204), 2));
        jPanel1.add(jToggleButton32, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 140, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton9ActionPerformed

    private void jToggleButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton10ActionPerformed

    private void jToggleButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton11ActionPerformed

    private void jToggleButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton25ActionPerformed

    private void jToggleButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton26ActionPerformed

    private void jToggleButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton27ActionPerformed

    private void jToggleButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton28ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton28ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton jToggleButton10;
    private javax.swing.JToggleButton jToggleButton11;
    private javax.swing.JToggleButton jToggleButton18;
    private javax.swing.JToggleButton jToggleButton25;
    private javax.swing.JToggleButton jToggleButton26;
    private javax.swing.JToggleButton jToggleButton27;
    private javax.swing.JToggleButton jToggleButton28;
    private javax.swing.JToggleButton jToggleButton29;
    private javax.swing.JToggleButton jToggleButton30;
    private javax.swing.JToggleButton jToggleButton31;
    private javax.swing.JToggleButton jToggleButton32;
    private javax.swing.JToggleButton jToggleButton33;
    private javax.swing.JToggleButton jToggleButton34;
    private javax.swing.JToggleButton jToggleButton35;
    private javax.swing.JToggleButton jToggleButton36;
    private javax.swing.JToggleButton jToggleButton9;
    // End of variables declaration//GEN-END:variables
}
