
import java.awt.Color;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author farhaan
 */
import javax.swing.JOptionPane;
public class User_Details extends javax.swing.JInternalFrame {

    /**
     * Creates new form User_Details
     */
    Color DefaultColor,ClickedColor;
    public User_Details() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui=(BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        DefaultColor = new Color(0,153,204);
        ClickedColor = new Color(102,204,255);
        
        u3.setBackground(DefaultColor);
        u3.setBackground(DefaultColor);
        u3.setBackground(DefaultColor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        u3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        u1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        u2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        uddestop = new javax.swing.JDesktopPane();

        setBackground(new java.awt.Color(0, 153, 204));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204), 2));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        u3.setBackground(new java.awt.Color(0, 153, 204));
        u3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        u3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                u3MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                u3MousePressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Log Out");
        u3.add(jLabel4);

        jPanel1.add(u3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 230, 40));

        u1.setBackground(new java.awt.Color(0, 153, 204));
        u1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        u1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                u1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                u1MousePressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Contact Us");
        u1.add(jLabel5);

        jPanel1.add(u1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 230, 40));

        u2.setBackground(new java.awt.Color(0, 153, 204));
        u2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        u2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                u2MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                u2MousePressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Customize");
        u2.add(jLabel6);

        jPanel1.add(u2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 230, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 440));

        javax.swing.GroupLayout uddestopLayout = new javax.swing.GroupLayout(uddestop);
        uddestop.setLayout(uddestopLayout);
        uddestopLayout.setHorizontalGroup(
            uddestopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );
        uddestopLayout.setVerticalGroup(
            uddestopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );

        getContentPane().add(uddestop, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 440, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void u3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_u3MouseClicked
        // TODO add your handling code here:
        int a=JOptionPane.showConfirmDialog(null,"Do you want to close this application","Select",JOptionPane.YES_NO_OPTION);
        if(a==0){
            System.exit(0);
        }
    }//GEN-LAST:event_u3MouseClicked

    private void u3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_u3MousePressed
        // TODO add your handling code here:
        u1.setBackground(DefaultColor);
        u2.setBackground(DefaultColor);
        u3.setBackground(ClickedColor);
    }//GEN-LAST:event_u3MousePressed

    private void u1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_u1MouseClicked
        // TODO add your handling code here:
        Contactus ud=new Contactus();
        uddestop.removeAll();
        uddestop.add(ud).setVisible(true);
    }//GEN-LAST:event_u1MouseClicked

    private void u1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_u1MousePressed
        // TODO add your handling code here:
        u1.setBackground(ClickedColor);
        u2.setBackground(DefaultColor);
        u3.setBackground(DefaultColor);
    }//GEN-LAST:event_u1MousePressed

    private void u2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_u2MouseClicked
        // TODO add your handling code here:
        Customize ud=new Customize();
        uddestop.removeAll();
        uddestop.add(ud).setVisible(true);
    }//GEN-LAST:event_u2MouseClicked

    private void u2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_u2MousePressed
        // TODO add your handling code here:
        u1.setBackground(DefaultColor);
        u2.setBackground(ClickedColor);
        u3.setBackground(DefaultColor);
    }//GEN-LAST:event_u2MousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel u1;
    private javax.swing.JPanel u2;
    private javax.swing.JPanel u3;
    private javax.swing.JDesktopPane uddestop;
    // End of variables declaration//GEN-END:variables
}
