
import javax.swing.plaf.basic.BasicInternalFrameUI;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author farhaan
 */
public class Weelyassignment extends javax.swing.JInternalFrame {

    /**
     * Creates new form Weelyassignment
     */
    public Weelyassignment() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui=(BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jToggleButton9 = new javax.swing.JToggleButton();
        jToggleButton10 = new javax.swing.JToggleButton();
        jToggleButton11 = new javax.swing.JToggleButton();
        jToggleButton12 = new javax.swing.JToggleButton();
        jToggleButton13 = new javax.swing.JToggleButton();
        jToggleButton14 = new javax.swing.JToggleButton();
        jToggleButton15 = new javax.swing.JToggleButton();
        jToggleButton16 = new javax.swing.JToggleButton();
        jToggleButton17 = new javax.swing.JToggleButton();
        jToggleButton18 = new javax.swing.JToggleButton();
        jToggleButton19 = new javax.swing.JToggleButton();
        jToggleButton20 = new javax.swing.JToggleButton();
        jToggleButton21 = new javax.swing.JToggleButton();
        jToggleButton22 = new javax.swing.JToggleButton();
        jToggleButton23 = new javax.swing.JToggleButton();
        jToggleButton24 = new javax.swing.JToggleButton();

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToggleButton9.setBackground(new java.awt.Color(0, 153, 204));
        buttonGroup1.add(jToggleButton9);
        jToggleButton9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jToggleButton9.setText("Week: 2 Ass");
        jToggleButton9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204), 2));
        jToggleButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 120, -1));

        jToggleButton10.setBackground(new java.awt.Color(0, 153, 204));
        buttonGroup1.add(jToggleButton10);
        jToggleButton10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jToggleButton10.setText("Week: 3 Ass");
        jToggleButton10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204), 2));
        jPanel1.add(jToggleButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 120, -1));

        jToggleButton11.setBackground(new java.awt.Color(0, 153, 204));
        buttonGroup1.add(jToggleButton11);
        jToggleButton11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jToggleButton11.setText("Week: 4 Ass");
        jToggleButton11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204), 2));
        jToggleButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton11ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 120, -1));

        jToggleButton12.setBackground(new java.awt.Color(0, 153, 204));
        buttonGroup1.add(jToggleButton12);
        jToggleButton12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jToggleButton12.setText("Week: 5 Ass");
        jToggleButton12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204), 2));
        jToggleButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton12ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 120, -1));

        jToggleButton13.setBackground(new java.awt.Color(0, 153, 204));
        buttonGroup1.add(jToggleButton13);
        jToggleButton13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jToggleButton13.setText("Week: 11 Ass");
        jToggleButton13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204), 2));
        jPanel1.add(jToggleButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 120, -1));

        jToggleButton14.setBackground(new java.awt.Color(0, 153, 204));
        buttonGroup1.add(jToggleButton14);
        jToggleButton14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jToggleButton14.setText("Week: 9 Ass");
        jToggleButton14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204), 2));
        jPanel1.add(jToggleButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 120, -1));

        jToggleButton15.setBackground(new java.awt.Color(0, 153, 204));
        buttonGroup1.add(jToggleButton15);
        jToggleButton15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jToggleButton15.setText("Week: 10 Ass");
        jToggleButton15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204), 2));
        jPanel1.add(jToggleButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 120, -1));

        jToggleButton16.setBackground(new java.awt.Color(0, 153, 204));
        buttonGroup1.add(jToggleButton16);
        jToggleButton16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jToggleButton16.setText("Week: 12 Ass");
        jToggleButton16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204), 2));
        jPanel1.add(jToggleButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 120, -1));

        jToggleButton17.setBackground(new java.awt.Color(0, 153, 204));
        buttonGroup1.add(jToggleButton17);
        jToggleButton17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jToggleButton17.setText("Week: 13 Ass");
        jToggleButton17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204), 2));
        jPanel1.add(jToggleButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 120, -1));

        jToggleButton18.setBackground(new java.awt.Color(0, 153, 204));
        buttonGroup1.add(jToggleButton18);
        jToggleButton18.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jToggleButton18.setText("Week: 1 Ass");
        jToggleButton18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204), 2));
        jPanel1.add(jToggleButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 120, -1));

        jToggleButton19.setBackground(new java.awt.Color(0, 153, 204));
        buttonGroup1.add(jToggleButton19);
        jToggleButton19.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jToggleButton19.setText("Week: 14 Ass");
        jToggleButton19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204), 2));
        jPanel1.add(jToggleButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 120, -1));

        jToggleButton20.setBackground(new java.awt.Color(0, 153, 204));
        buttonGroup1.add(jToggleButton20);
        jToggleButton20.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jToggleButton20.setText("Week: 7 Ass");
        jToggleButton20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204), 2));
        jToggleButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton20ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 120, -1));

        jToggleButton21.setBackground(new java.awt.Color(0, 153, 204));
        buttonGroup1.add(jToggleButton21);
        jToggleButton21.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jToggleButton21.setText("Week: 15 Ass");
        jToggleButton21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204), 2));
        jPanel1.add(jToggleButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 120, -1));

        jToggleButton22.setBackground(new java.awt.Color(0, 153, 204));
        buttonGroup1.add(jToggleButton22);
        jToggleButton22.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jToggleButton22.setText("Week: 16 Ass");
        jToggleButton22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204), 2));
        jPanel1.add(jToggleButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 120, -1));

        jToggleButton23.setBackground(new java.awt.Color(0, 153, 204));
        buttonGroup1.add(jToggleButton23);
        jToggleButton23.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jToggleButton23.setText("Week: 6 Ass");
        jToggleButton23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204), 2));
        jPanel1.add(jToggleButton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 120, -1));

        jToggleButton24.setBackground(new java.awt.Color(0, 153, 204));
        buttonGroup1.add(jToggleButton24);
        jToggleButton24.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jToggleButton24.setText("Week: 8 Ass");
        jToggleButton24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204), 2));
        jPanel1.add(jToggleButton24, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 120, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton11ActionPerformed

    private void jToggleButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton9ActionPerformed

    private void jToggleButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton12ActionPerformed

    private void jToggleButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton20ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton jToggleButton10;
    private javax.swing.JToggleButton jToggleButton11;
    private javax.swing.JToggleButton jToggleButton12;
    private javax.swing.JToggleButton jToggleButton13;
    private javax.swing.JToggleButton jToggleButton14;
    private javax.swing.JToggleButton jToggleButton15;
    private javax.swing.JToggleButton jToggleButton16;
    private javax.swing.JToggleButton jToggleButton17;
    private javax.swing.JToggleButton jToggleButton18;
    private javax.swing.JToggleButton jToggleButton19;
    private javax.swing.JToggleButton jToggleButton20;
    private javax.swing.JToggleButton jToggleButton21;
    private javax.swing.JToggleButton jToggleButton22;
    private javax.swing.JToggleButton jToggleButton23;
    private javax.swing.JToggleButton jToggleButton24;
    private javax.swing.JToggleButton jToggleButton9;
    // End of variables declaration//GEN-END:variables
}
